const svgsNames = [
	'add-to-cart',
	'bandwidth',
	'cash',
	'chatgpt',
	'circular-arrow',
	'clock',
	'coin',
	'coupon',
	'discount',
	'dot-arrow',
	'dot-right-arrow',
	'down-arrow',
	'error',
	'eye-off',
	'eye-show',
	'hard-drive',
	'help',
	'information',
	'letter-open',
	'magnifire',
	'midjourney',
	'numbers',
	'ok-mark',
	'pay-per-click',
	'pay',
	'perplexity',
	'poe',
	'processor',
	'ram',
	'right-arrow',
	'stopwatch',
	'triangular-arrowhead',
	'waiting-list',
	'wallet',
	'warning-circle',
	'warning-triangle',
] as const;

export type SvgsNames = typeof svgsNames[number];
